# Generated by Django 6.0.2 on 2026-02-18 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('CONF', 'Conference Room'), ('MEET', 'Meeting Room'), ('TRAIN', 'Training Room')], default='MEET', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['room_id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='CONFIRMED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.userprofile')),
            ],
            options={
                'ordering': ['-booking_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_number', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_COMPLETED', 'Booking Completed'), ('ACCESS_ATTEMPT', 'Access Attempt'), ('USER_ADDED', 'User Added'), ('ROOM_MODIFIED', 'Room Modified')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='bookings.booking')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='bookings.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='bookings.userprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('GRANTED', 'Granted'), ('DENIED', 'Denied')], max_length=20)),
                ('access_datetime', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_attempts', to='bookings.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_attempts', to='bookings.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Access',
                'ordering': ['-access_datetime'],
            },
        ),
    ]
