# Generated by Django 6.0.2 on 2026-03-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('organisation_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('unique_access_code', models.CharField(help_text='Unique code for organisation access', max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('fee', models.DecimalField(decimal_places=2, help_text='Monthly fee', max_digits=10)),
                ('number_of_users', models.PositiveIntegerField(default=0, help_text='Total users in organisation')),
                ('number_of_rooms', models.PositiveIntegerField(default=0, help_text='Total rooms owned by organisation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='bookings.organisation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bookings.organisation'),
        ),
    ]
