# Generated by Django 5.1.6 on 2026-04-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_organisation_room_organisation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='number_of_users',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
