# Generated by Django 6.0.2 on 2026-04-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_duration_minutes_booking_is_recurring_and_more'),
        ('bookings', '0004_notification'),
    ]

    operations = [
    ]
