# Generated by GitHub Copilot on 2026-04-24

from django.db import migrations, models


def _populate_restored_fields(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Organisation = apps.get_model('bookings', 'Organisation')
    UserProfile = apps.get_model('bookings', 'UserProfile')

    used_emails = set(
        email
        for email in UserProfile.objects.exclude(email__isnull=True).values_list('email', flat=True)
        if email
    )

    for profile in UserProfile.objects.all():
        user = User.objects.filter(pk=profile.user_id).first()

        if user is not None:
            full_name = f"{user.first_name} {user.last_name}".strip()
            fallback_name = user.username or f"User {profile.user_id}"
            profile.name = full_name or fallback_name

            candidate_email = (user.email or '').strip().lower()
            if not candidate_email:
                candidate_email = f"user{profile.user_id}@example.com"
        else:
            profile.name = f"User {profile.user_id}"
            candidate_email = f"user{profile.user_id}@example.com"

        if profile.email and profile.email.strip():
            candidate_email = profile.email.strip().lower()

        base_local, _, base_domain = candidate_email.partition('@')
        if not base_domain:
            base_local = base_local or f"user{profile.user_id}"
            base_domain = 'example.com'

        unique_email = f"{base_local}@{base_domain}"
        suffix = 1
        while unique_email in used_emails:
            suffix += 1
            unique_email = f"{base_local}{suffix}@{base_domain}"

        used_emails.add(unique_email)
        profile.email = unique_email
        profile.save(update_fields=['name', 'email'])

    for organisation in Organisation.objects.all():
        if organisation.password is None:
            organisation.password = ''

        organisation.number_of_users = UserProfile.objects.filter(organisation_id=organisation.organisation_id).count()
        organisation.save(update_fields=['password', 'number_of_users'])


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_merge_20260424_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='number_of_users',
            field=models.PositiveIntegerField(default=0, help_text='Total users in organisation'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.RunPython(_populate_restored_fields, _noop_reverse),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['name']},
        ),
    ]
